import type { NextPage } from "next";
import Head from "next/head";
import CreatorCarousel from "../components/creator/CreatorCarousel";
import FAQ from "../components/FAQ";
import Footer from "../components/Footer";
import FrontHero from "../components/FrontHero";
import Header from "../components/Header";
import NFTCollection from "../components/NFTCollection";
import Partners from "../components/Partners";
import { trpc } from "../utils/trpc";

const Home: NextPage = () => {

  return (
    <div >
      <Head>
        <title>Babylon traders</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-gradient-to-tr min-h-screen from-primary via-secondary to-neutral" >
        <div className="max-w-7xl mx-auto">
          <section>
            <FrontHero />
          </section>
          <section>
            <Partners />
          </section>
          <section>
            <div className="mt-24">
              <div className="text-center">
                <h1 className="text-5xl font-bold font-poppins">Featured Collections</h1>
                <p className="font-poppins text-lg mt-5">Lorem ipsum dolor sit amet</p>
              </div>
              <NFTCollection />
            </div>
          </section>
          <section>
            <CreatorCarousel />
          </section>
          <section>
            <FAQ />
          </section>
        </div>
      </main>
    </div>
  );
};

export default Home;

