import type { NextPage } from "next";
import Head from "next/head";
import CreatorCarousel from "../components/CreatorCarousel";
import FAQ from "../components/FAQ";
import Footer from "../components/Footer";
import FrontHero from "../components/FrontHero";
import Header from "../components/Header";
import NFTCollection from "../components/NFTCollection";
import Partners from "../components/Partners";
import { trpc } from "../utils/trpc";

const Home: NextPage = () => {

  return (
    <>
      <Head>
        <title>Babylon traders</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link
          href="https://fonts.googleapis.com/css2?family=Playfair+Display:ital,wght@0,500;0,700;1,400&family=Poppins:wght@400;500;700&display=swap"
          rel="stylesheet" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-gradient-to-tr min-h-screen from-primary via-secondary to-neutral" >
        <div className="max-w-7xl mx-auto">
          <Header />
          <section>
            <FrontHero />
          </section>
          <section>
            <Partners />
          </section>
          <section>
            <NFTCollection />
          </section>
          <section>
            <CreatorCarousel />
          </section>
          <section>
            <FAQ />
          </section>
        </div>
        <section>
          <Footer />
        </section>
      </main>
    </>
  );
};

export default Home;

