[build]
  base = "nft-trading/"
  command = "npm run build"
  publish = ".next"
  environment = {
    DATABASE_URL="postgresql://postgres:Lapiovra123@db.wxfxfbsmjpypdyozuxhk.supabase.co:5432/postgres",
    SUPABASE_PRISMA_PROXY_URL="prisma://aws-eu-central-1.prisma-data.com/?api_key=-HewgasAXqdthaA3ydNQIhkOqQinND4jNAHkeXE0vJaU7menh3hsR_dp2rQ6Tg30",
    NEXTAUTH_SECRET="5eC0Y7TtiaZVChiE1MAp2RxdnoYV7sBW",
    NEXTAUTH_URL="http://localhost:3000",
    DISCORD_CLIENT_ID="1017434703575388220",
    DISCORD_CLIENT_SECRET="BjpXegSHQ1Q1DATyl5U46hEucij1BaXw",
    NFT_PORT_API_KEY="7f0ad73f-368b-4350-b2f7-d0dea1752a2f",
    UBIQUITY_API_KEY="IneLQ6C5i9Kd4XilEj962OvbkoE7NMzLxgDjIWkn2vLwrHOZ",
    RARIFY_API_KEY="ae11c010-1901-4cca-9293-8ee5ceb28270",
    INFURA_API_KEY="3c67fe207a61416399e15c182158bbb4"
  }

[[plugins]]
  package = "@netlify/plugin-nextjs"