import FAQRow from "./FAQRow"

function FAQ() {
    return (
        <div className="mt-24">
            <div className="text-center">
                <h1 className="text-5xl font-bold font-poppins">FAQs</h1>
                <p className="font-poppins text-lg">Any questions?</p>
            </div>
            <div className="grid grid-cols-2 gap-4 py-4 p-2">
                <div className="flex flex-col space-y-3">
                    <FAQRow tabIndex={0}
                        question="What is BazaarMarket?"
                        answer="BazaarMarket is a bartering marketplace for NFTs. We are a community of artists, collectors, and curators. We are building a platform that allows artists and users to trade their NFTs."
                    />
                    <FAQRow
                        question="How does it work?"
                        answer="Find the NFT that you want to trade on a user profile. Click on Trade Now and send a trade request. The user will receive a notification and can accept or decline the trade. If the trade is accepted, the NFTs will be swapped."
                        tabIndex={1} />
                    <FAQRow
                        question="How do I sign in to the website?"
                        answer="You can sign in by clicking on the Sign In button on the top right corner of the page. A new page will open where you can sign in with your Discord account."
                        tabIndex={2} />
                </div>
                <div className="flex flex-col space-y-3">
                    <FAQRow
                        question="How do I mint a pack of NFTs?"
                        answer="You can mint a pack of NFTs by clicking on the Claim button on the top of the page. After a successful claim a mint button will appear, by clicking it and signing the transaction you will receive a pack of NFTs for free."
                        tabIndex={3} />
                    <FAQRow
                        question="What are Diffemons?"
                        answer="Diffemons are NFTs that were generated using the Stable Diffusion text-to-image model while the creatures' names and personalities were generated by GPT3. They are a part of our NFT project."
                        tabIndex={4} />
                    <FAQRow
                        question="What chains are supported?"
                        answer="We currently support Polygon and Ethereum mainnet. We are planning to add more chains in the future."
                        tabIndex={5} />
                </div>
            </div>
        </div>
    )
}

export default FAQ